# Generated by Django 5.2.8 on 2025-11-06 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('emissions', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.emissiontype')),
            ],
        ),
    ]
